export const REGISTRATION_COUNTRIES = [
  "United States",
  "India",
  "United Kingdom",
  "Canada",
  "Australia",
  "Singapore",
  "United Arab Emirates",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Ireland",
  "Switzerland",
  "Japan",
  "South Korea",
  "Malaysia",
  "Thailand",
  "Saudi Arabia",
  "Qatar",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Mexico",
  "Brazil",
  "Argentina",
  "Turkey",
  "Indonesia",
  "Philippines",
  "New Zealand",
];
